# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_investing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='number_of_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
    ]
