# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_investing', '0003_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fantasy_investing.Portfolio'),
        ),
    ]
