# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_investing', '0004_stock_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_investing.Portfolio'),
        ),
    ]
