# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_investing', '0005_investor'),
        ('fantasy_investing', '0005_auto_20170404_1848'),
    ]

    operations = [
    ]
